### ISSUE TITLE
Whitespace between content page's title and accordion content when body field isn't used

### ISSUE THREAD

**Issue by Detzner** [ATLAS-Illinois/Illinois-Framework-Theme#866]
Almost all pages used an accordion paragraph for the content. There was 1.25 - 1.5 inches of space between the page title and the heading for the accordion (see attached). It looks like there's a div inserted above the paragraph where content begins, using this code:
<div class="field field--name-body field--type-text-with-summary field--label-hidden il-formatted background--color--white field__item"><style type="text/css">
<![CDATA[/* >

/*--><!]]>*/
</style></div>

 To fix this I added CSS to have negative margin under the page title, and then gave the paragraph block under the title a transparent background so that it wouldn't obscure the title. But I don't know why that div.field--name-body is there creating an empty 3/4" of space.

Example of the issue is at https://drupal-sandbox.webtheme.illinois.edu/accordion-without-sidebar-or-body-content

![image](https://user-images.githubusercontent.com/56594946/222270487-6e375910-23a0-4d2b-b8f9-7ef96cd6f53f.png)

**Comment by mwllr** [comment]
Same as issue #815 @wrg20

**Comment by wrg20** [comment]
@Detzner - do you have a page where this is happening that I can reference?  I think I know what you are talking about but I just wanted to make sure. I would like for you to be able to remove the negative margin.  I think the problem is probably when there is no body content entered but the div is still being rendered (based on your description).

**Comment by Detzner** [comment]
Hi Bill—

The page https://isg.illinois.edu/about is a typical example. The h1 title has a negative margin-bottom of -1.75em. In the editing page there is an empty editing field for the Body.

Thanks—

Dick

From: William Gutierrez ***@***.***>
Reply-To: web-illinois/illinois_framework_theme ***@***.***>
Date: Tuesday, December 13, 2022 at 2:37 PM
To: web-illinois/illinois_framework_theme ***@***.***>
Cc: "Detzner, Richard" ***@***.***>, Mention ***@***.***>
Subject: Re: [web-illinois/illinois_framework_theme] extra white space under the page titles on the content pages on isg.illinois.edu (Issue #866)


@Detzner<https://urldefense.com/v3/__https:/github.com/Detzner__;!!DZ3fjg!8VqCxPX8Cgjhm0Pk6UaMkhFNQOrAXjCAPIZNwCjsfG5EljjgTANlQg3B3b0sMPzFkDXqeVqSPD2A4EGII1B2_UDw1Rw$> - do you have a page where this is happening that I can reference? I think I know what you are talking about but I just wanted to make sure. I would like for you to be able to remove the negative margin. I think the problem is probably when there is no body content entered but the div is still being rendered (based on your description).

**Comment by wrg20** [comment]
Thanks @Detzner.  

@mwllr - I can't remember if we intended to indent the title or have it inline with the block I.
![image](https://user-images.githubusercontent.com/1544079/207651313-29751b9c-2915-44e4-9efa-39bad04f6ec4.png)

As for the spacing issue.  It appears that we are not doing a check on the body field to see if there is content or not.  I will have to do a check on that field and that should resolve the spacing issue.  The screenshot below shows Dick's website with no content in the body field for the page.  
![image](https://user-images.githubusercontent.com/1544079/207652052-34487cda-c0fb-49f8-9bfb-968d8be21f4b.png)

**Comment by trubach** [comment]
I think this issue is not resolved and not related to #815. I created a page with the issue at:

https://drupal-sandbox.webtheme.illinois.edu/accordion-without-sidebar-or-body-content

and it still has a lot of padding between the title and first text. I didn't see the <style> tag that Dick sees on his site, but it still looks like we should try and shrink the padding between the page heading and the paragraph heading when the body field isn't used.

**Comment by trubach** [comment]
Closing - now tracked in issue #988
